version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"  # LocalStack Gateway
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DYNAMODB_SHARE_DB=1
