import './global.scss';

export const metadata = {
    title: 'Welcome to cms',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className='flex-centered h-screen'>
                {children}
            </body>
        </html>
    );
}
