export enum CameraStatusEnum {
    ACTIVE = 'ACTIVE',
    PAUSED = 'PAUSED',
    IMAGE_PAUSE_PROCESSING = 'IMAGE_PAUSE_PROCESSING',
    IMAGE_PAUSE_ERROR = 'IMAGE_PAUSE_ERROR',
    IMAGE_RESUME_PROCESSING = 'IMAGE_RESUME_PROCESSING',
    IMAGE_RESUME_ERROR = 'IMAGE_RESUME_ERROR',
    IMAGE_CAPTURE_PROCESSING = 'IMAGE_CAPTURE_PROCESSING',
    IMAGE_CAPTURE_ERROR = 'IMAGE_CAPTURE_ERROR',
}
