export enum FirmwareUpdateStatusEnum {
    IDLE = 'IDLE',
    COMPLETED = 'COMPLETED',
    PENDING = 'PENDING',
    PAUSED = 'PAUSED',
    COMMAND_PROCESSING = 'COMMAND_PROCESSING',
    UPDATE_ERROR = 'UPDATE_ERROR',
    VERSION_MISMATCH = 'VERSION_MISMATCH',
}
